/**
 * Dizionario delle causali EssePaghe (tabella Causali Eventi dello Studio).
 *
 * Dati, non logica: e' l'elenco che il consulente usa in EssePaghe, estratto
 * dalla legenda del foglio presenze. Serve a due cose: proporre all'ufficio
 * solo codici che esistono davvero, e sapere se una causale viaggia nel record
 * 12 (eventi per periodo) o nel record 14 (eventi giornalieri).
 *
 * `obbligatorioRecord12` marca le causali che il consulente ha indicato come
 * obbligatorie per periodo (malattia, maternita', infortunio). `frequente`
 * marca quelle realmente viste in uso, cosi' il selettore le mette in cima.
 *
 * Generato dal CSV del pacchetto EssePaghe: non modificare a mano riga per
 * riga, aggiornare la fonte e rigenerare.
 */

export type FamigliaCausale = 'evento' | 'straordinario';
export type TipoRecordEvento = '12' | '14';

export interface CausaleEssePaghe {
  codice: string;
  descrizione: string;
  famiglia: FamigliaCausale;
  /** Record di destinazione predefinito. */
  record: TipoRecordEvento;
  /** Il consulente lo vuole per periodo, non giorno per giorno. */
  obbligatorioRecord12: boolean;
  /** Causale vista in uso: il selettore la propone per prima. */
  frequente: boolean;
}

export const CAUSALI_ESSEPAGHE: readonly CausaleEssePaghe[] = [
  { codice: '1A', descrizione: 'CIG - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1B', descrizione: 'CIG ev.meteo - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1C', descrizione: 'CIGS - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1D', descrizione: 'CIG in deroga/Emergenziale', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1F', descrizione: 'Ass.Ord.FIS/FSB - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1G', descrizione: 'Ass.Sol.FIS/FSB - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1H', descrizione: 'CIGS/Cds - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1I', descrizione: 'Ass.Ord.FSB(mass.lordo) - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1J', descrizione: 'Ass.Ord.FSB ARTIG.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1K', descrizione: 'Ass.Sol.FSB ARTIG.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1L', descrizione: 'Ass.Sol.FSB(mass.lordo) - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1M', descrizione: 'CIG in deroga/Emergenziale/sì ratei', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '1O', descrizione: 'ISU - rich.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2A', descrizione: 'CIG - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2B', descrizione: 'CIG ev.meteo - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2C', descrizione: 'CIGS - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2E', descrizione: 'Ass.Ord. c/F.do Credito - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2F', descrizione: 'Ass.Ord.FIS/FSB - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2G', descrizione: 'Ass.Sol.FIS/FSB - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2H', descrizione: 'CIGS/Cds - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2I', descrizione: 'Ass.Ord.FSB(mass.lordo) - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2L', descrizione: 'Ass.Sol.FSB(mass.lordo) - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '2O', descrizione: 'ISU - aut.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '8E', descrizione: 'Formazione apprendista esterna', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '8I', descrizione: 'Formazione apprendista interna', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '9A', descrizione: 'Assenza non retribuita', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A0', descrizione: 'Assenza ingiustificata', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A1', descrizione: 'Assenza non retribuita', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A2', descrizione: 'Assenza x sciopero', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A3', descrizione: 'Assemblea', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A4', descrizione: 'Sospens.caut.retribuita', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A5', descrizione: 'Sospens. disciplinare', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A7', descrizione: 'Assenza giustif. x C.E./-- Tfr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A8', descrizione: 'Assenza giustif. x C.E./=Tfr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'A9', descrizione: 'Ore non lavorate', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AA', descrizione: 'Periodo prec.te l\'assunzione', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AB', descrizione: 'Assenza edile/utile x compl.orario', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AC', descrizione: 'Assenza G.O.R./Dmag', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AD', descrizione: 'Assenza giustif. x C.E.con acc.to/-- Tfr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AE', descrizione: 'Assenza giustif. x C.E con acc.to./=Tfr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AJ', descrizione: 'Aspettativa sindacale', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AL', descrizione: 'Allattamento', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AM', descrizione: 'Assenza x succ.migrazione', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AN', descrizione: 'Assenza x prec.rapporto altra filiale', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AP', descrizione: 'Sospensione non retribuita', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AQ', descrizione: 'Sospensione crisi aziend.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AR', descrizione: 'Assenza ingiustificata', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AS', descrizione: 'Aspettativa', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AV', descrizione: 'Assenza con prestazioni Ente bilat', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AX', descrizione: 'Assenza a carico Ente bilat.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AY', descrizione: 'Aspettativa per car. elettive', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'AZ', descrizione: 'Cisoa G.O.R./ev.atmosferici rid.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B1', descrizione: 'Perm.orari L.104/92 c.2/XB3', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B2', descrizione: 'Perm.orari L.104/92 c.6/QB5', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B3', descrizione: 'Perm.orari L.106/2025 art.2', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B4', descrizione: 'Perm.orari L.106/2025 art.2 (x figlio)', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B5', descrizione: 'Perm.giornal. L.104/92 c.6/TA1', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B6', descrizione: 'Perm. L.104/92- Enti pubbl.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B7', descrizione: 'Perm.giornal. L.104/92 c.3/RA1', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'B8', descrizione: 'Mal. bambino sino 3 anni', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'B9', descrizione: 'Mal. bambino 3-14 anni', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BA', descrizione: 'Perm.L.104/92-agric.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BB', descrizione: 'Perm.L.104/92-agric./pag.dir.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BO', descrizione: 'Banca ore godute', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BQ', descrizione: 'Perm.orari L.106/2025 art.2 / Enti pubbl.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BR', descrizione: 'Perm.orari L.106/2025 art.2/DMAG', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BS', descrizione: 'Perm.orari L.106/2025 art.2/(x figlio)/DMAG', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BT', descrizione: 'Perm.orari L.106/2025 art.2/No den.(rimb.diretto)', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'BU', descrizione: 'Allattamento-agric./pag.dir.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'C0', descrizione: 'Cong.parentale (lutto/infermità) art.4 C.1', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: true },
  { codice: 'C1', descrizione: 'Cong.parentale (gravi motivi fam) art.4/C.2', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'C2', descrizione: 'Cong. x formazione art.5 L.53/00', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'C3', descrizione: 'Cong.straord.D.Lgs.151/2001/MD1', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'C6', descrizione: 'Cong.paternità obbl../fig.', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'CA', descrizione: 'Corso formazione app.sti', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CB', descrizione: 'Formazione esterna (Scuola) - app.1L', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CF', descrizione: 'Corso formazione', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CG', descrizione: 'Formazione interna - app.1L', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CH', descrizione: 'Sosp.ne crisi az.appr.sti c/Ceav', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CI', descrizione: 'CIG autorizzata (non operativa da 5/2018)', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CN', descrizione: 'Formazione interna 10%-app.1L (fac.)', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CO', descrizione: 'Corso formazione Obbl.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CQ', descrizione: 'CIG appr.Ceav-Cedaiier', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CR', descrizione: 'CIG ev.meteo appr.Ceav-Cedaiier', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CT', descrizione: 'CIG agricoltura/Impiegati', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CV', descrizione: 'CIG appr.edili', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CW', descrizione: 'CIG ev.meteo appr.ed.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'CZ', descrizione: 'CIG agricoltura/operai', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DG', descrizione: 'Cong.violenza di genere', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'DH', descrizione: 'Cong.violenza di genere/metà orario', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'DJ', descrizione: 'Distacco sindacale', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DM', descrizione: 'Donaz.midollo osseo', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DS', descrizione: 'Donazione sangue', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DT', descrizione: 'Inidoneità donazione sangue', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DV', descrizione: 'Donaz.midollo osseo/DMAG OTI', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DW', descrizione: 'Donaz.midollo osseo/OTD agric.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DX', descrizione: 'Donazione sangue/OTD agric.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DY', descrizione: 'Inidoneità Don.Sangue/DMAG OTI', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'DZ', descrizione: 'Donazione sangue/DMAG OTI', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'EJ', descrizione: 'CIG NON autorizzata - ev.meteo/FSB', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'EX', descrizione: 'CIG NON autorizzata/FSB', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'EY', descrizione: 'CIGS NON autorizzata/FSB', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'F0', descrizione: 'Ferie ope.edili a.c.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'F1', descrizione: 'Ferie ope.edili', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'F2', descrizione: 'R.o.l. ope.edili', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'F3', descrizione: 'Anticipo r.o.l./p.a.r. edili', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'FC', descrizione: 'Ferie a.c.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'FE', descrizione: 'Ferie', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'FG', descrizione: 'Festività godute', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'FL', descrizione: 'Flessibilità goduta', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'FX', descrizione: 'Festività', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'FY', descrizione: 'Semifestività', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'GD', descrizione: 'Disponibilità lav.intermitt.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'I1', descrizione: '1°gg.infortunio', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'IC', descrizione: 'Infortunio:ricaduta/continuazione', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'IN', descrizione: 'Infortunio', famiglia: 'evento', record: '12', obbligatorioRecord12: true, frequente: false },
  { codice: 'LE', descrizione: 'Servizio di leva', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'M+', descrizione: 'Mat.fac.ind.80% (MW+MF)', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'M1', descrizione: 'Cong.matrimoniale (tutto ditta)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'M2', descrizione: 'Cong.matrimoniale (Inps+ ditta)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'M@', descrizione: 'Mat.fac.ind.80%(MW+MG/MH)', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MA', descrizione: 'Mat.:gg. no integr.ditta', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MC', descrizione: 'Malattia: ricaduta/continuazione', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'MD', descrizione: 'Mal.:gg.indennizzati solo ditta', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MF', descrizione: 'Maternità facoltativa', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'MG', descrizione: 'Mat.facoltativa /ore/No contr.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MH', descrizione: 'Mat.facoltativa /ore/Si contr.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MI', descrizione: 'Cong.matrimoniale (Inps)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'ML', descrizione: 'Malattia', famiglia: 'evento', record: '12', obbligatorioRecord12: true, frequente: true },
  { codice: 'MN', descrizione: 'Mal.:gg.non indennizzati', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MO', descrizione: 'Maternità obbligatoria', famiglia: 'evento', record: '12', obbligatorioRecord12: true, frequente: false },
  { codice: 'MP', descrizione: 'Prolung.mater.facoltativa/YA1', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MQ', descrizione: 'Maternità: parto fort.prematuro', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'MR', descrizione: 'Malattia: ricov.ospedaliero', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'MS', descrizione: 'Mat.facoltativa /ore/DMAG', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MT', descrizione: 'Prolung.mater.facoltativa/YA2', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'MW', descrizione: 'Maternità facoltativa (ind.80%)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'NA', descrizione: 'C. parentale (lim 6 m/6°-14° anno)/b.G', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NB', descrizione: 'C. parentale (lim 6 m/6°-14° a)/b.O/no contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NC', descrizione: 'C. parentale (lim 6 m/6°-14° a)/b.O/si contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'ND', descrizione: 'C. parentale (lim 7/8/9 m/fino 14° anno)/b.G', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NE', descrizione: 'C. parentale (lim7/8/9 m/fino 14°a)/b.O/no contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NF', descrizione: 'C. parentale (lim7/8/9 m/fino 14°a)/b.O/si contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NG', descrizione: 'C. parentale (+9 -lim 10/11 m/fino 8° a)/b.G', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NH', descrizione: 'C. parentale(+9-lim 10/11 m/fino 8°a)/b.O/no contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NI', descrizione: 'C. parentale(+9-lim 10/11 m/fino 8°a)/b.O/si contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NJ', descrizione: 'C. parentale n/r(+9 -lim 10/11 m/fino 8°a)/b.G', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NK', descrizione: 'C. parentale n/r(+9-lim10/11m/fino 8°a)/b.O/no con', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NL', descrizione: 'C. parentale n/r(+9-lim10/11m/fino 8°a)/b.O/si con', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NM', descrizione: 'C. parentale (+9 -lim 10/11 m/8°-14° a)/b.G', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NN', descrizione: 'C. parentale(+9-lim 10/11 m/8°-14°a)/b.O/no contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NO', descrizione: 'C. parentale(+9-lim 10/11 m/8°-14°a)/b.O/si contr', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NP', descrizione: 'C. parentale n/r(+9 -lim 10/11 m/8°-14°a)/b.G', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NQ', descrizione: 'C. parentale n/r(+9 -lim10/11m/8°-14°a)/b.O/no con', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NR', descrizione: 'C. parentale n/r(+9 -lim10/11m/8°-14°a)/b.O/si con', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'NS', descrizione: 'Cong.paternità obbl.(PF1)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'NT', descrizione: 'Cong.paternità obbl./DMAG(A1)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'NU', descrizione: 'Cong.paternità obbl./DMAG(A2)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'NV', descrizione: 'Cong.paternità obbl./DMAG(A3)', famiglia: 'evento', record: '12', obbligatorioRecord12: false, frequente: false },
  { codice: 'P0', descrizione: 'Permesso non retribuito', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'P1', descrizione: 'Permesso retribuito', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'P2', descrizione: 'Permesso sindacale', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'P3', descrizione: 'Permesso x carica pubblica', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'P4', descrizione: 'Permesso x elezioni', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'P5', descrizione: 'Permesso di studio', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'P6', descrizione: 'Permesso esami', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'P7', descrizione: 'Perm. x calamità naturale', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'P8', descrizione: 'Perm.contr.pren.art.14 D.Lgs.151/2001', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'PA', descrizione: 'Permessi ex.fest. a.c.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'PB', descrizione: 'Permessi rol/par a.c.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'PF', descrizione: 'Permessi ex festività', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'PR', descrizione: 'Permessi r.o.l/p.a.r.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'PV', descrizione: 'Vacanza scolastica', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'QL', descrizione: 'Qualificato', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'R0', descrizione: 'Riposo compensativo', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'Y2', descrizione: 'Ore ordinarie distacco', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'ZX', descrizione: 'Utile per gestione multi c/c', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'ZY', descrizione: 'Assenza x gestione doppio ced.', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'ZZ', descrizione: 'Periodo success. cessazione', famiglia: 'evento', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '#F', descrizione: 'No festività', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '#G', descrizione: 'Festività non goduta', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: '90', descrizione: 'Straordinario', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'F4', descrizione: 'R.o.l. ope.edili or.inv.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'FA', descrizione: 'Flessibilità in accantonamento', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'FD', descrizione: '2^ Festività nel giorno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L0', descrizione: 'Lav.supplementare (p.time)', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'L1', descrizione: 'Lav.supplementare', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L2', descrizione: 'Lav.ecced.orario contr.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L3', descrizione: 'Lav.supplementare (p.time)', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L4', descrizione: 'Lavoro notturno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L5', descrizione: 'Lavoro notturno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L7', descrizione: 'Lavoro festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L8', descrizione: 'Lavoro notturno/festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'L9', descrizione: 'Lav.ecced.orario contr.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'LA', descrizione: 'Lavoro disagevole', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'LB', descrizione: 'Prest.aggiuntive art.21/Ccnl - 1/50', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'LC', descrizione: 'Prest.aggiuntive art.21/Ccnl - 1/25', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'LP', descrizione: 'Prolungamento orario', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'QN', descrizione: 'Quarantena/Permanenza domiciliare - no tutele', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'S0', descrizione: 'Straordinario', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'S1', descrizione: 'Straordinario diurno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'S3', descrizione: 'Straord. in riposo non dom.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'S4', descrizione: 'Straordinario notturno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'S5', descrizione: 'Straordinario notturno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'S7', descrizione: 'Straordinario festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'S8', descrizione: 'Straordinario nott./festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'S9', descrizione: 'Straordinario sabato', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'SB', descrizione: 'Straordinario a banca ore', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'SF', descrizione: 'Straordinario forfettizzato', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'SW', descrizione: 'Smart working', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'SX', descrizione: 'Straordinario (solo x ctr.agg.vo)', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'T1', descrizione: 'Magg.turno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'T3', descrizione: 'Magg.turno notturno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'T4', descrizione: 'Magg.turno festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'T5', descrizione: 'Magg.turno notturno/festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'V1', descrizione: 'Ore viaggio/maggioraz.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: true },
  { codice: 'V2', descrizione: 'Ore viaggio/straordin.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'W0', descrizione: 'Fortetizzazione 24,99%', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'W1', descrizione: 'Assemblea extra orario', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'X0', descrizione: 'Magg.lavoro supplementare', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'X1', descrizione: 'Maggiorazione', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'X4', descrizione: 'Magg.lavoro notturno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'X5', descrizione: 'Magg.lavoro notturno', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'X7', descrizione: 'Magg.lavoro festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'X8', descrizione: 'Magg.lavoro notturno/festivo', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'X9', descrizione: 'Magg.lavoro di sabato', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'XA', descrizione: 'Magg.lavoro disagiato', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'XD', descrizione: 'Magg.lavoro domenicale', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'XE', descrizione: 'Magg.lavoro domenicale', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'XQ', descrizione: 'Magg.lavoro domenicale', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'XR', descrizione: 'Magg.lavoro domenicale rip.comp.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'Y0', descrizione: 'Ore rif.to full-time x intermitt.', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
  { codice: 'Y1', descrizione: 'Ore "perse" p/t agevolato', famiglia: 'straordinario', record: '14', obbligatorioRecord12: false, frequente: false },
];

const PER_CODICE = new Map(CAUSALI_ESSEPAGHE.map((c) => [c.codice, c]));

export function causaleEssePaghe(codice: string): CausaleEssePaghe | undefined {
  return PER_CODICE.get(codice.trim().toUpperCase());
}

export function descrizioneCausale(codice: string): string {
  return PER_CODICE.get(codice.trim().toUpperCase())?.descrizione ?? codice;
}

/** Codici ammessi dal tracciato ma fuori tabella (orario del giorno, cantiere). */
export const CAUSALI_TECNICHE = ['OT', 'OR', 'CC'] as const;

